<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>dns.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Title>DNS Changer</Title>
    <FileVersion>1.0.2</FileVersion>
    <AssemblyVersion>1.0.2</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="dns.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.3" />
  </ItemGroup>

</Project>
